name: Sync to Apidog

on:
  push:
    branches: [main, master]
    paths: ['services/**/openapi.yaml']
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g @apidevtools/swagger-cli
      - run: |
          for spec in services/*/openapi.yaml; do
            swagger-cli validate "$spec"
          done

  sync:
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyyaml requests
      - env:
          APIDOG_TOKEN: ${{ secrets.APIDOG_TOKEN }}
          APIDOG_PROJECT_ID: ${{ secrets.APIDOG_PROJECT_ID }}
        run: python scripts/sync_to_apidog.py
